server:
  port: 8080


spring:
  datasource:
   url: jdbc:mysql://localhost:3306/myapp?useSSL=false
   username: root
   password: admin
  jpa:
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect

